name_nbs = input("Enter your name: ")
age_nbs = input("Enter your age: ")
course_nbs = input("Enter your course: ")
university_nbs = input("Enter your university: ")
print("\n----- STUDENT PROFILE -----")
print("Name:", name_nbs)
print("Age:", age_nbs)
print("Course:", course_nbs)
print("University:", university_nbs)
